# **Importing Dataset**

In [2]:
!pip install -q kaggle

In [3]:
import kagglehub

path = kagglehub.dataset_download(
    "martj42/international-football-results-from-1872-to-2017"
)

print(path)

Using Colab cache for faster access to the 'international-football-results-from-1872-to-2017' dataset.
/kaggle/input/international-football-results-from-1872-to-2017

In [4]:
import os

os.listdir(path)

['former_names.csv', 'goalscorers.csv', 'shootouts.csv', 'results.csv']

In [5]:
import pandas as pd
import os

results_path = os.path.join(path, "results.csv")

df = pd.read_csv(results_path)
df.head()
df.tail()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
49515,2026-07-11,Argentina,Switzerland,3.0,1.0,FIFA World Cup,Kansas City,United States,True
49516,2026-07-14,France,Spain,0.0,2.0,FIFA World Cup,Arlington,United States,True
49517,2026-07-15,England,Argentina,1.0,2.0,FIFA World Cup,Atlanta,United States,True
49518,2026-07-18,France,England,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True
49519,2026-07-19,Spain,Argentina,NaN,NaN,FIFA World Cup,East Rutherford,United States,True

# **Data Cleaning**

## Cleaning Tasks Performed

- Loaded the `results.csv` dataset into a Pandas DataFrame.
- Inspected the dataset using `.head()`, `.tail()`, `.info()`, and `.shape()`.
- Checked for missing values using `.isnull().sum()`.
- Checked for duplicate records and removed them if necessary.
- Converted the `date` column from string format to `datetime`.
- Extracted useful date features such as **year**, **month**, and **day**.
- Verified that `home_score` and `away_score` contain valid (non-negative) values.
- Examined team names and tournament names for consistency.
- Verified the `neutral` column and converted it to a numerical format if required.
- Saved the cleaned dataset for the next stages of the project.

In [6]:
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49520 entries, 0 to 49519
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        49520 non-null  object
 1   home_team   49520 non-null  object
 2   away_team   49520 non-null  object
 3   home_score  49518 non-null  float64
 4   away_score  49518 non-null  float64
 5   tournament  49520 non-null  object
 6   city        49520 non-null  object
 7   country     49520 non-null  object
 8   neutral     49520 non-null  bool
dtypes: bool(1), float64(2), object(6)
memory usage: 3.1+ MB

In [7]:
df.isnull().sum()

date          0
home_team     0
away_team     0
home_score    2
away_score    2
tournament    0
city          0
country       0
neutral       0
dtype: int64

In [8]:
df = df.iloc[:-2]
df.isnull().sum()

date          0
home_team     0
away_team     0
home_score    0
away_score    0
tournament    0
city          0
country       0
neutral       0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df["date"] = pd.to_datetime(df["date"])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49518 entries, 0 to 49517
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        49518 non-null  datetime64[ns]
 1   home_team   49518 non-null  object
 2   away_team   49518 non-null  object
 3   home_score  49518 non-null  float64
 4   away_score  49518 non-null  float64
 5   tournament  49518 non-null  object
 6   city        49518 non-null  object
 7   country     49518 non-null  object
 8   neutral     49518 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(2), object(5)
memory usage: 3.1+ MB

In [11]:
df["year"] = df["date"].dt.year
df["month"] = df["date"].dt.month
df["day"] = df["date"].dt.day
df.head

<bound method NDFrame.head of             date  home_team    away_team  home_score  away_score  \
0     1872-11-30   Scotland      England         0.0         0.0
1     1873-03-08    England     Scotland         4.0         2.0
2     1874-03-07   Scotland      England         2.0         1.0
3     1875-03-06    England     Scotland         2.0         2.0
4     1876-03-04   Scotland      England         3.0         0.0
...          ...        ...          ...         ...         ...
49513 2026-07-10      Spain      Belgium         2.0         1.0
49514 2026-07-11     Norway      England         1.0         2.0
49515 2026-07-11  Argentina  Switzerland         3.0         1.0
49516 2026-07-14     France        Spain         0.0         2.0
49517 2026-07-15    England    Argentina         1.0         2.0

           tournament           city        country  neutral  year  month  day
0            Friendly        Glasgow       Scotland    False  1872     11   30
1            Friendly         London        England    False  1873      3    8
2            Friendly        Glasgow       Scotland    False  1874      3    7
3            Friendly         London        England    False  1875      3    6
4            Friendly        Glasgow       Scotland    False  1876      3    4
...               ...            ...            ...      ...   ...    ...  ...
49513  FIFA World Cup      Inglewood  United States     True  2026      7   10
49514  FIFA World Cup  Miami Gardens  United States     True  2026      7   11
49515  FIFA World Cup    Kansas City  United States     True  2026      7   11
49516  FIFA World Cup      Arlington  United States     True  2026      7   14
49517  FIFA World Cup        Atlanta  United States     True  2026      7   15

[49518 rows x 12 columns]>

In [12]:
df["home_team"].nunique() #unique hometeam count

328

In [13]:
df["away_team"].nunique() #unique awayteam count

322

In [14]:
sorted(df["home_team"].unique())[:]

['Abkhazia',
 'Afghanistan',
 'Albania',
 'Alderney',
 'Algeria',
 'American Samoa',
 'Andalusia',
 'Andorra',
 'Angola',
 'Anguilla',
 'Antigua and Barbuda',
 'Arameans Suryoye',
 'Argentina',
 'Armenia',
 'Artsakh',
 'Aruba',
 'Australia',
 'Austria',
 'Aymara',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barawa',
 'Barbados',
 'Basque Country',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Biafra',
 'Bolivia',
 'Bonaire',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'British Virgin Islands',
 'Brittany',
 'Brunei',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Canary Islands',
 'Canton Ticino',
 'Cape Verde',
 'Cascadia',
 'Catalonia',
 'Cayman Islands',
 'Central African Republic',
 'Central Spain',
 'Chad',
 'Chagos Islands',
 'Chameria',
 'Chechnya',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Congo',
 'Cook Islands',
 'Corsica',
 'Costa Rica',
 'County of Nice',
 'Croatia',
 'Cuba',
 'Curaçao',
 'Cyprus',
 'Czech Republic',
 'Czechoslovakia',
 'DR Congo',
 'Darfur',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Donetsk PR',
 'Délvidék',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Elba Island',
 'Ellan Vannin',
 'England',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Eswatini',
 'Ethiopia',
 'Falkland Islands',
 'Faroe Islands',
 'Felvidék',
 'Fiji',
 'Finland',
 'France',
 'Franconia',
 'French Guiana',
 'Frøya',
 'Gabon',
 'Galicia',
 'Gambia',
 'Georgia',
 'German DR',
 'Germany',
 'Ghana',
 'Gibraltar',
 'Gotland',
 'Gozo',
 'Greece',
 'Greenland',
 'Grenada',
 'Guadeloupe',
 'Guam',
 'Guatemala',
 'Guernsey',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Găgăuzia',
 'Haiti',
 'Hitra',
 'Hmong',
 'Honduras',
 'Hong Kong',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Iraqi Kurdistan',
 'Isle of Man',
 'Isle of Wight',
 'Israel',
 'Italy',
 'Ivory Coast',
 'Jamaica',
 'Japan',
 'Jersey',
 'Jordan',
 'Kabylia',
 'Kazakhstan',
 'Kenya',
 'Kernow',
 'Kiribati',
 'Kosovo',
 'Kurdistan',
 'Kuwait',
 'Kyrgyzstan',
 'Kárpátalja',
 'Laos',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luhansk PR',
 'Luxembourg',
 'Macau',
 'Madagascar',
 'Madrid',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Manchukuo',
 'Mapuche',
 'Marshall Islands',
 'Martinique',
 'Matabeleland',
 'Mauritania',
 'Mauritius',
 'Mayotte',
 'Menorca',
 'Mexico',
 'Micronesia',
 'Moldova',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Montserrat',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nepal',
 'Netherlands',
 'New Caledonia',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'Niue',
 'North Korea',
 'North Macedonia',
 'North Vietnam',
 'Northern Cyprus',
 'Northern Ireland',
 'Northern Mariana Islands',
 'Norway',
 'Occitania',
 'Oman',
 'Orkney',
 'Padania',
 'Pakistan',
 'Palau',
 'Palestine',
 'Panama',
 'Panjab',
 'Papua New Guinea',
 'Paraguay',
 'Parishes of Jersey',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Provence',
 'Puerto Rico',
 'Qatar',
 'Quebec',
 'Raetia',
 'Republic of Ireland',
 'Republic of St. Pauli',
 'Rhodes',
 'Romani people',
 'Romania',
 'Rouet-Provence',
 'Russia',
 'Rwanda',
 'Ryūkyū',
 'Réunion',
 'Saare County',
 'Saarland',
 'Saint Barthélemy',
 'Saint Helena',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Martin',
 'Saint Pierre and Miquelon',
 'Saint Vincent and the Grenadines',
 'Samoa',
 'San Marino',
 'Sark',
 'Saudi Arabia',
 'Saugeais',
 'Scotland',
 'Sealand',
 'Seborga',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Shetland',
 'Sierra Leone',
 'Silesia',
 'Singapore',
 'Sint Maarten',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'Somaliland',
 'South Africa',
 'South Korea',
 'South Ossetia',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Sweden',
 'Switzerland',
 'Syria',
 'Székely Land',
 'Sápmi',
 'São Tomé and Príncipe',
 'Tahiti',
 'Taiwan',
 'Tajikistan',
 'Tamil Eelam',
 'Tanzania',
 'Thailand',
 'Tibet',
 'Timor-Leste',
 'Togo',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Turks and Caicos Islands',
 'Tuvalu',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Koreans in Japan',
 'United States',
 'United States Virgin Islands',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Vatican City',
 'Venezuela',
 'Vietnam',
 'Vietnam Republic',
 'Wales',
 'Wallis Islands and Futuna',
 'West Papua',
 'Western Armenia',
 'Western Australia',
 'Western Isles',
 'Western Sahara',
 'Yemen',
 'Yemen DPR',
 'Ynys Môn',
 'Yorkshire',
 'Yoruba Nation',
 'Yugoslavia',
 'Zambia',
 'Zanzibar',
 'Zimbabwe',
 'Åland Islands']

In [15]:
df["tournament"].value_counts()

tournament
Friendly                                18387
FIFA World Cup qualification             8771
UEFA Euro qualification                  2824
African Cup of Nations qualification     2327
FIFA World Cup                           1066
                                        ...
Copa Confraternidad                         1
ConIFA Challenger Cup                       1
Benedikt Fontana Cup                        1
CONIFA World Cup qualification              1
South Asian Super Cup                       1
Name: count, Length: 201, dtype: int64

In [16]:
(df["home_score"] < 0).sum()
(df["away_score"] < 0).sum()

np.int64(0)

In [17]:
df.describe()

,date,home_score,away_score,year,month,day
count,49518,49518.000000,49518.000000,49518.000000,49518.000000,49518.000000
mean,1994-05-31 19:38:53.260632448,1.757179,1.182338,1993.884507,6.902116,15.212589
min,1872-11-30 00:00:00,0.000000,0.000000,1872.000000,1.000000,1.000000
25%,1980-09-15 06:00:00,1.000000,0.000000,1980.000000,4.000000,8.000000
50%,2000-07-22 12:00:00,1.000000,1.000000,2000.000000,7.000000,14.000000
75%,2013-07-28 00:00:00,2.000000,2.000000,2013.000000,10.000000,23.000000
max,2026-07-15 00:00:00,31.000000,21.000000,2026.000000,12.000000,31.000000
std,NaN,1.773730,1.401927,25.444022,3.230540,8.585299

In [18]:
df["neutral"].value_counts()

neutral
False    36364
True     13154
Name: count, dtype: int64

In [19]:
df["neutral"] = df["neutral"].astype(int)
#converting it into numeric for easier model training

In [20]:
df.to_csv("cleaned_results.csv", index=False)
df.tail()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,year,month,day
49513,2026-07-10,Spain,Belgium,2.0,1.0,FIFA World Cup,Inglewood,United States,1,2026,7,10
49514,2026-07-11,Norway,England,1.0,2.0,FIFA World Cup,Miami Gardens,United States,1,2026,7,11
49515,2026-07-11,Argentina,Switzerland,3.0,1.0,FIFA World Cup,Kansas City,United States,1,2026,7,11
49516,2026-07-14,France,Spain,0.0,2.0,FIFA World Cup,Arlington,United States,1,2026,7,14
49517,2026-07-15,England,Argentina,1.0,2.0,FIFA World Cup,Atlanta,United States,1,2026,7,15

In [21]:
df.dtypes

date          datetime64[ns]
home_team             object
away_team             object
home_score           float64
away_score           float64
tournament            object
city                  object
country               object
neutral                int64
year                   int32
month                  int32
day                    int32
dtype: object

# **Creating Target Variable**

In [22]:
def get_result(row):
  if row["home_score"] > row["away_score"]:
    return "Home_win"
  elif row["home_score"] < row["away_score"]:
    return "Away_win"
  else:
    return "Draw"
df["result"] = df.apply(get_result, axis=1)
df.tail()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,year,month,day,result
49513,2026-07-10,Spain,Belgium,2.0,1.0,FIFA World Cup,Inglewood,United States,1,2026,7,10,Home_win
49514,2026-07-11,Norway,England,1.0,2.0,FIFA World Cup,Miami Gardens,United States,1,2026,7,11,Away_win
49515,2026-07-11,Argentina,Switzerland,3.0,1.0,FIFA World Cup,Kansas City,United States,1,2026,7,11,Home_win
49516,2026-07-14,France,Spain,0.0,2.0,FIFA World Cup,Arlington,United States,1,2026,7,14,Away_win
49517,2026-07-15,England,Argentina,1.0,2.0,FIFA World Cup,Atlanta,United States,1,2026,7,15,Away_win

# **Creating Basic Predictors**

In [23]:
Predictors = [
    "home_team",
    "away_team",
    "tournament",
    "country",
    "neutral",
    "year",
    "month"
]

# **Spliting Train & Test Split**

In [24]:
train = df[df["year"] < 2023].copy()
test = df[df["year"] >= 2023].copy()

# **Encoding Categorical Variable**

In [25]:
from sklearn.preprocessing import OrdinalEncoder

Categorical_Cols = [
    "home_team",
    "away_team",
    "tournament",
    "country"
]

encoder = OrdinalEncoder(
    handle_unknown="use_encoded_value",
    unknown_value=-1
)

train[Categorical_Cols] = encoder.fit_transform(train[Categorical_Cols])
test[Categorical_Cols] = encoder.transform(test[Categorical_Cols])
train.tail()
test.tail()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,year,month,day,result
49513,2026-07-10,268.0,29.0,2.0,1.0,77.0,Inglewood,248.0,1,2026,7,10,Home_win
49514,2026-07-11,203.0,88.0,1.0,2.0,77.0,Miami Gardens,248.0,1,2026,7,11,Away_win
49515,2026-07-11,12.0,268.0,3.0,1.0,77.0,Kansas City,248.0,1,2026,7,11,Home_win
49516,2026-07-14,97.0,262.0,0.0,2.0,77.0,Arlington,248.0,1,2026,7,14,Away_win
49517,2026-07-15,86.0,13.0,1.0,2.0,77.0,Atlanta,248.0,1,2026,7,15,Away_win

# **Random Forest Model**

In [26]:
X_train = train[Predictors]
y_train = train["result"]

X_test = test[Predictors]
y_test = test["result"]

print(y_train)

0            Draw
1        Home_win
2        Home_win
3            Draw
4        Home_win
           ...
45805    Home_win
45806    Home_win
45807    Home_win
45808        Draw
45809        Draw
Name: result, Length: 45810, dtype: object

In [27]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=750,
    max_depth=15,
    min_samples_leaf=2,
    random_state=42
)

model.fit(X_train, y_train)

RandomForestClassifier(max_depth=15, min_samples_leaf=2, n_estimators=750,
                       random_state=42)

In [28]:
from sklearn.metrics import accuracy_score

predictions = model.predict(X_test)

accuracy = accuracy_score(y_test, predictions)
print(accuracy*100)

50.0269687162891

# **XGBoost**

In [29]:
from xgboost import XGBClassifier
from sklearn.preprocessing import LabelEncoder

xgb_model = XGBClassifier(
    objective="multi:softmax",
    num_class=3,
    n_estimators=400,
    learning_rate=0.05,
    max_depth=6,
    random_state=42
)

#encoding y_train for XGBOOST
Label_encoder = LabelEncoder()
y_train_encoded = Label_encoder.fit_transform(y_train)
y_test_encoded = Label_encoder.transform(y_test)

xgb_model.fit(X_train, y_train_encoded)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=400,
              n_jobs=None, num_class=3, ...)

In [30]:
from sklearn.metrics import accuracy_score

predictions_XGBoost = xgb_model.predict(X_test)

accuracy = accuracy_score(y_test_encoded, predictions_XGBoost)
print(accuracy*100)

53.61380798274003

# **CatBoost**

In [31]:
pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.4)
Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl (97.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 10.1 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.10

In [32]:
from catboost import CatBoostClassifier

cat_model = CatBoostClassifier(
    iterations=5000,
    learning_rate=0.05,
    depth=6,
    loss_function="MultiClass",
    random_seed=42,
    verbose=100
)

cat_model.fit(X_train, y_train)

0:	learn: 1.0923799	total: 90.6ms	remaining: 7m 32s
100:	learn: 1.0148736	total: 2.94s	remaining: 2m 22s
200:	learn: 1.0006708	total: 9.07s	remaining: 3m 36s
300:	learn: 0.9862150	total: 16.7s	remaining: 4m 20s
400:	learn: 0.9736010	total: 22.2s	remaining: 4m 14s
500:	learn: 0.9634200	total: 28.2s	remaining: 4m 12s
600:	learn: 0.9547187	total: 31.2s	remaining: 3m 48s
700:	learn: 0.9473103	total: 33.2s	remaining: 3m 23s
800:	learn: 0.9403559	total: 35.2s	remaining: 3m 4s
900:	learn: 0.9335991	total: 38s	remaining: 2m 52s
1000:	learn: 0.9273297	total: 40.7s	remaining: 2m 42s
1100:	learn: 0.9213378	total: 42.7s	remaining: 2m 31s
1200:	learn: 0.9157947	total: 44.7s	remaining: 2m 21s
1300:	learn: 0.9107386	total: 46.7s	remaining: 2m 12s
1400:	learn: 0.9057229	total: 48.7s	remaining: 2m 5s
1500:	learn: 0.9008715	total: 51.7s	remaining: 2m
1600:	learn: 0.8962828	total: 54.2s	remaining: 1m 55s
1700:	learn: 0.8917653	total: 56.2s	remaining: 1m 49s
1800:	learn: 0.8873844	total: 58.3s	remaining: 1m 43s
1900:	learn: 0.8831545	total: 1m	remaining: 1m 38s
2000:	learn: 0.8789253	total: 1m 2s	remaining: 1m 33s
2100:	learn: 0.8750486	total: 1m 5s	remaining: 1m 30s
2200:	learn: 0.8711093	total: 1m 7s	remaining: 1m 26s
2300:	learn: 0.8673063	total: 1m 9s	remaining: 1m 21s
2400:	learn: 0.8637736	total: 1m 11s	remaining: 1m 17s
2500:	learn: 0.8603927	total: 1m 13s	remaining: 1m 13s
2600:	learn: 0.8569507	total: 1m 15s	remaining: 1m 9s
2700:	learn: 0.8535454	total: 1m 19s	remaining: 1m 7s
2800:	learn: 0.8502104	total: 1m 21s	remaining: 1m 3s
2900:	learn: 0.8470542	total: 1m 23s	remaining: 1m
3000:	learn: 0.8438267	total: 1m 25s	remaining: 56.9s
3100:	learn: 0.8407350	total: 1m 27s	remaining: 53.5s
3200:	learn: 0.8375231	total: 1m 29s	remaining: 50.3s
3300:	learn: 0.8345238	total: 1m 32s	remaining: 47.8s
3400:	learn: 0.8314729	total: 1m 34s	remaining: 44.6s
3500:	learn: 0.8284825	total: 1m 36s	remaining: 41.5s
3600:	learn: 0.8257334	total: 1m 38s	remaining: 38.4s
3700:	learn: 0.8229847	total: 1m 40s	remaining: 35.4s
3800:	learn: 0.8201548	total: 1m 43s	remaining: 32.6s
3900:	learn: 0.8176350	total: 1m 46s	remaining: 30s
4000:	learn: 0.8150161	total: 1m 48s	remaining: 27.1s
4100:	learn: 0.8122316	total: 1m 50s	remaining: 24.2s
4200:	learn: 0.8096754	total: 1m 52s	remaining: 21.4s
4300:	learn: 0.8072045	total: 1m 54s	remaining: 18.6s
4400:	learn: 0.8047114	total: 1m 57s	remaining: 16s
4500:	learn: 0.8022322	total: 2m 1s	remaining: 13.5s
4600:	learn: 0.7996562	total: 2m 3s	remaining: 10.7s
4700:	learn: 0.7971099	total: 2m 5s	remaining: 7.98s
4800:	learn: 0.7946114	total: 2m 7s	remaining: 5.29s
4900:	learn: 0.7922555	total: 2m 10s	remaining: 2.63s
4999:	learn: 0.7899035	total: 2m 12s	remaining: 0us

CatBoostClassifier(depth=6, iterations=5000, learning_rate=0.05, loss_function='MultiClass', random_seed=42, verbose=100)

In [33]:
from sklearn.metrics import accuracy_score

predictions_CatBoost = cat_model.predict(X_test)

accuracy = accuracy_score(y_test, predictions_CatBoost)
print(accuracy*100)

53.66774541531824

# **Feature Engineering**

Creating recent form feature for each team

1.   Calculates the points from last 5 matches
2.   Win = 3, Lose = 0 & Draw = 0
3.   Also Another feature of Recent Avg point also been created

In [44]:
from collections import defaultdict

team_points = defaultdict(list)

home_recent_points = []
away_recent_points = []

WINDOW = 5

for _, row in df.iterrows():

    home = row["home_team"]
    away = row["away_team"]

    home_history = team_points[home][-WINDOW:]
    away_history = team_points[away][-WINDOW:]

    home_recent_points.append(sum(home_history))
    away_recent_points.append(sum(away_history))

    if row["home_score"] > row["away_score"]:

        team_points[home].append(3)
        team_points[away].append(0)

    elif row["home_score"] < row["away_score"]:

        team_points[home].append(0)
        team_points[away].append(3)

    else:

        team_points[home].append(1)
        team_points[away].append(1)


df["home_recent_points"] = home_recent_points
df["away_recent_points"] = away_recent_points
df.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,year,month,day,result,home_recent_points,away_recent_points
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,0,1872,11,30,Draw,0,0
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,0,1873,3,8,Home_win,1,1
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,0,1874,3,7,Home_win,1,4
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,0,1875,3,6,Draw,4,4
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,0,1876,3,4,Home_win,5,5

In [46]:
team_points = defaultdict(list)

avg_home_recent_points = []
avg_away_recent_points = []

WINDOW = 5

for _, row in df.iterrows():

    home = row["home_team"]
    away = row["away_team"]

    home_history = team_points[home][-WINDOW:]
    away_history = team_points[away][-WINDOW:]

    if len(home_history) == 0:
      avg_home_recent_points.append(0)
    else:
      avg_home_recent_points.append(sum(home_history) / len(home_history))

    if len(away_history) == 0:
      avg_away_recent_points.append(0)
    else:
      avg_away_recent_points.append(sum(away_history) / len(away_history))


    if row["home_score"] > row["away_score"]:

        team_points[home].append(3)
        team_points[away].append(0)

    elif row["home_score"] < row["away_score"]:

        team_points[home].append(0)
        team_points[away].append(3)

    else:

        team_points[home].append(1)
        team_points[away].append(1)


df["avg_home_recent_points"] = avg_home_recent_points
df["avg_away_recent_points"] = avg_away_recent_points
df.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,year,month,day,result,home_recent_points,away_recent_points,avg_home_recent_points,avg_away_recent_points
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,0,1872,11,30,Draw,0,0,0.000000,0.000000
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,0,1873,3,8,Home_win,1,1,1.000000,1.000000
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,0,1874,3,7,Home_win,1,4,0.500000,2.000000
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,0,1875,3,6,Draw,4,4,1.333333,1.333333
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,0,1876,3,4,Home_win,5,5,1.250000,1.250000

Creating Head to Head statistics Features

In [47]:

head_to_head = defaultdict(
    lambda: {
        "team1_wins": 0,
        "team2_wins": 0,
        "draws": 0
    }
)

home_h2h_wins = []
away_h2h_wins = []
h2h_draws = []

for _, row in df.iterrows():

    home = row["home_team"]
    away = row["away_team"]

    pair = tuple(sorted([home, away]))

    stats = head_to_head[pair]

    # Which team is team1?
    if pair[0] == home:

        home_h2h_wins.append(stats["team1_wins"])
        away_h2h_wins.append(stats["team2_wins"])

    else:

        home_h2h_wins.append(stats["team2_wins"])
        away_h2h_wins.append(stats["team1_wins"])

    h2h_draws.append(stats["draws"])

    if row["home_score"] > row["away_score"]:

        if pair[0] == home:
            stats["team1_wins"] += 1
        else:
            stats["team2_wins"] += 1

    elif row["home_score"] < row["away_score"]:

        if pair[0] == away:
            stats["team1_wins"] += 1
        else:
            stats["team2_wins"] += 1

    else:

        stats["draws"] += 1


df["home_h2h_wins"] = home_h2h_wins
df["away_h2h_wins"] = away_h2h_wins
df["h2h_draws"] = h2h_draws
df.tail()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,year,month,day,result,home_recent_points,away_recent_points,avg_home_recent_points,avg_away_recent_points,home_h2h_wins,away_h2h_wins,h2h_draws
49513,2026-07-10,Spain,Belgium,2.0,1.0,FIFA World Cup,Inglewood,United States,1,2026,7,10,Home_win,13,11,2.6,2.2,11,5,6
49514,2026-07-11,Norway,England,1.0,2.0,FIFA World Cup,Miami Gardens,United States,1,2026,7,11,Away_win,12,13,2.4,2.6,2,7,3
49515,2026-07-11,Argentina,Switzerland,3.0,1.0,FIFA World Cup,Kansas City,United States,1,2026,7,11,Home_win,15,11,3.0,2.2,5,0,2
49516,2026-07-14,France,Spain,0.0,2.0,FIFA World Cup,Arlington,United States,1,2026,7,14,Away_win,15,15,3.0,3.0,13,18,7
49517,2026-07-15,England,Argentina,1.0,2.0,FIFA World Cup,Atlanta,United States,1,2026,7,15,Away_win,13,15,2.6,3.0,6,3,6

In [50]:
from collections import defaultdict

df = df.sort_values("date").reset_index(drop=True)

head_to_head = defaultdict(
    lambda: {
        "team1_goals": 0,
        "team2_goals": 0,
        "team1_wins": 0,
        "team2_wins": 0,
        "draws": 0,
        "matches": 0,
        "last_result": None
    }
)

home_h2h_goals_scored = []
away_h2h_goals_scored = []

home_h2h_goal_difference = []

last_h2h_result = []

h2h_matches_played = []

for _, row in df.iterrows():

    home = row["home_team"]
    away = row["away_team"]

    home_score = row["home_score"]
    away_score = row["away_score"]

    pair = tuple(sorted([home, away]))

    stats = head_to_head[pair]


    if pair[0] == home:

        home_goals = stats["team1_goals"]
        away_goals = stats["team2_goals"]

    else:

        home_goals = stats["team2_goals"]
        away_goals = stats["team1_goals"]

    home_h2h_goals_scored.append(home_goals)

    away_h2h_goals_scored.append(away_goals)

    home_h2h_goal_difference.append(home_goals - away_goals)

    h2h_matches_played.append(stats["matches"])


    if stats["last_result"] is None:

        last_h2h_result.append("No History")

    else:

        if pair[0] == home:

            last_h2h_result.append(stats["last_result"])

        else:

            if stats["last_result"] == "Win":
                last_h2h_result.append("Loss")

            elif stats["last_result"] == "Loss":
                last_h2h_result.append("Win")

            else:
                last_h2h_result.append("Draw")


    if pair[0] == home:

        stats["team1_goals"] += home_score
        stats["team2_goals"] += away_score

    else:

        stats["team1_goals"] += away_score
        stats["team2_goals"] += home_score

    stats["matches"] += 1

    if home_score > away_score:

        if pair[0] == home:

            stats["team1_wins"] += 1
            stats["last_result"] = "Win"

        else:

            stats["team2_wins"] += 1
            stats["last_result"] = "Loss"

    elif home_score < away_score:

        if pair[0] == home:

            stats["team2_wins"] += 1
            stats["last_result"] = "Loss"

        else:

            stats["team1_wins"] += 1
            stats["last_result"] = "Win"

    else:

        stats["draws"] += 1
        stats["last_result"] = "Draw"


df["home_h2h_goals_scored"] = home_h2h_goals_scored
df["away_h2h_goals_scored"] = away_h2h_goals_scored

df["home_h2h_goal_difference"] = home_h2h_goal_difference

df["last_h2h_result"] = last_h2h_result

df["h2h_matches_played"] = h2h_matches_played
df.tail()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,year,...,avg_home_recent_points,avg_away_recent_points,home_h2h_wins,away_h2h_wins,h2h_draws,home_h2h_goals_scored,away_h2h_goals_scored,home_h2h_goal_difference,last_h2h_result,h2h_matches_played
49513,2026-07-10,Spain,Belgium,2.0,1.0,FIFA World Cup,Inglewood,United States,1,2026,...,2.6,2.2,11,5,6,44.0,22.0,22.0,Win,22
49514,2026-07-11,Norway,England,1.0,2.0,FIFA World Cup,Miami Gardens,United States,1,2026,...,2.4,2.6,2,7,3,7.0,28.0,-21.0,Loss,12
49515,2026-07-11,Argentina,Switzerland,3.0,1.0,FIFA World Cup,Kansas City,United States,1,2026,...,3.0,2.2,5,0,2,15.0,3.0,12.0,Win,7
49516,2026-07-14,France,Spain,0.0,2.0,FIFA World Cup,Arlington,United States,1,2026,...,3.0,3.0,13,18,7,44.0,71.0,-27.0,Loss,38
49517,2026-07-15,England,Argentina,1.0,2.0,FIFA World Cup,Atlanta,United States,1,2026,...,2.6,3.0,6,3,6,22.0,18.0,4.0,Win,15

In [52]:
import numpy as np

df["home_h2h_avg_goals"] = np.where(
    df["h2h_matches_played"] == 0,
    0,
    df["home_h2h_goals_scored"] / df["h2h_matches_played"]
)

df["away_h2h_avg_goals"] = np.where(
    df["h2h_matches_played"] == 0,
    0,
    df["away_h2h_goals_scored"] / df["h2h_matches_played"]
)

df.tail()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,year,...,home_h2h_wins,away_h2h_wins,h2h_draws,home_h2h_goals_scored,away_h2h_goals_scored,home_h2h_goal_difference,last_h2h_result,h2h_matches_played,home_h2h_avg_goals,away_h2h_avg_goals
49513,2026-07-10,Spain,Belgium,2.0,1.0,FIFA World Cup,Inglewood,United States,1,2026,...,11,5,6,44.0,22.0,22.0,Win,22,2.000000,1.000000
49514,2026-07-11,Norway,England,1.0,2.0,FIFA World Cup,Miami Gardens,United States,1,2026,...,2,7,3,7.0,28.0,-21.0,Loss,12,0.583333,2.333333
49515,2026-07-11,Argentina,Switzerland,3.0,1.0,FIFA World Cup,Kansas City,United States,1,2026,...,5,0,2,15.0,3.0,12.0,Win,7,2.142857,0.428571
49516,2026-07-14,France,Spain,0.0,2.0,FIFA World Cup,Arlington,United States,1,2026,...,13,18,7,44.0,71.0,-27.0,Loss,38,1.157895,1.868421
49517,2026-07-15,England,Argentina,1.0,2.0,FIFA World Cup,Atlanta,United States,1,2026,...,6,3,6,22.0,18.0,4.0,Win,15,1.466667,1.200000